import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1768478099382 implements MigrationInterface {
    name = 'InitMigration1768478099382'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "indicator_scores" DROP CONSTRAINT "indicator_scores_submission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP CONSTRAINT "indicator_score_history_submission_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_manual_score_updates_submission_indicator"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_manual_score_updates_submission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_manual_score_updates_indicator"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_manual_score_updates_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_scores_indicator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_scores_submission_indicator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_scores_submission"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_score_history_indicator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_score_history_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_score_history_submission_indicator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_indicator_score_history_submission"`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" DROP CONSTRAINT "indicator_scores_submission_indicator_unique"`);
        await queryRunner.query(`COMMENT ON TABLE "manual_score_updates" IS NULL`);
        await queryRunner.query(`ALTER TABLE "submissions" ALTER COLUMN "attached_files" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" DROP COLUMN "indicatorCode"`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ADD "indicatorCode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "manual_score_updates"."systemScore" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "manual_score_updates"."manualUpdatedScore" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "manual_score_updates"."updateReason" IS NULL`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" DROP COLUMN "indicatorCode"`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ADD "indicatorCode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "indicatorCode"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "indicatorCode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "updatedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "updateReason"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "updateReason" character varying`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "indicatorStatus"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "indicatorStatus" character varying`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_87b976b681dd1d4e35431b5af1" ON "manual_score_updates" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c84ba20b3ebbf49e5d43545c46" ON "manual_score_updates" ("indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a6fb69befc5265808e2f30ed" ON "manual_score_updates" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f16da9224e81e0ff4b23a85792" ON "manual_score_updates" ("submissionId", "indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea301c4015e84f971d3024b913" ON "indicator_scores" ("submissionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c48a7e0479ea983d1d16eb2f6d" ON "indicator_scores" ("submissionId", "indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_e35c4253575712f488716633a1" ON "indicator_score_history" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f41807ab8c4513ca104de06568" ON "indicator_score_history" ("indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c753b797a5cbf78faa58a31fb" ON "indicator_score_history" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3335a77675793616c9a266c601" ON "indicator_score_history" ("submissionId", "indicatorCode") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_3335a77675793616c9a266c601"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c753b797a5cbf78faa58a31fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f41807ab8c4513ca104de06568"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e35c4253575712f488716633a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c48a7e0479ea983d1d16eb2f6d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea301c4015e84f971d3024b913"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f16da9224e81e0ff4b23a85792"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06a6fb69befc5265808e2f30ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c84ba20b3ebbf49e5d43545c46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b976b681dd1d4e35431b5af1"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "indicatorStatus"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "indicatorStatus" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "updateReason"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "updateReason" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "updatedBy" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "category" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" DROP COLUMN "indicatorCode"`);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD "indicatorCode" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ADD "category" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" DROP COLUMN "indicatorCode"`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ADD "indicatorCode" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "manual_score_updates"."updateReason" IS 'Reason provided by user for the manual update'`);
        await queryRunner.query(`COMMENT ON COLUMN "manual_score_updates"."manualUpdatedScore" IS 'The manually entered score by MOSPI_APPROVER'`);
        await queryRunner.query(`COMMENT ON COLUMN "manual_score_updates"."systemScore" IS 'The original system-generated score at the time of manual update'`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ADD "category" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" DROP COLUMN "indicatorCode"`);
        await queryRunner.query(`ALTER TABLE "manual_score_updates" ADD "indicatorCode" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "submissions" ALTER COLUMN "attached_files" SET DEFAULT '[]'`);
        await queryRunner.query(`COMMENT ON TABLE "manual_score_updates" IS 'Stores manual score updates made by MOSPI_APPROVER. System-generated scores remain in indicator_scores table and are not modified.'`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ADD CONSTRAINT "indicator_scores_submission_indicator_unique" UNIQUE ("submissionId", "indicatorCode")`);
        await queryRunner.query(`CREATE INDEX "idx_indicator_score_history_submission" ON "indicator_score_history" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "idx_indicator_score_history_submission_indicator" ON "indicator_score_history" ("indicatorCode", "submissionId") `);
        await queryRunner.query(`CREATE INDEX "idx_indicator_score_history_created_at" ON "indicator_score_history" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_indicator_score_history_indicator" ON "indicator_score_history" ("indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "idx_indicator_scores_submission" ON "indicator_scores" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "idx_indicator_scores_submission_indicator" ON "indicator_scores" ("indicatorCode", "submissionId") `);
        await queryRunner.query(`CREATE INDEX "idx_indicator_scores_indicator" ON "indicator_scores" ("indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_manual_score_updates_created" ON "manual_score_updates" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_manual_score_updates_indicator" ON "manual_score_updates" ("indicatorCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_manual_score_updates_submission" ON "manual_score_updates" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_manual_score_updates_submission_indicator" ON "manual_score_updates" ("indicatorCode", "submissionId") `);
        await queryRunner.query(`ALTER TABLE "indicator_score_history" ADD CONSTRAINT "indicator_score_history_submission_id_fkey" FOREIGN KEY ("submissionId") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "indicator_scores" ADD CONSTRAINT "indicator_scores_submission_id_fkey" FOREIGN KEY ("submissionId") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
